[features]
seeds = false
skip-lint = false
[programs.localnet]
multisig_wallet = "5wgwCaNBvEBz2LCxdL5nTZSab8wwDDpHfX8RaoW1jRpu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/shubh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
